export const MOKCatalog = [
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
  {
    id: 1,
    image: '/images/monuments/monuments5.png',
    description: 'A-02',
    name: 'Вертикальный памятник',
    price: 997,
  },
];
